#consulter fournisseurs

SELECT NOM, ADRESSE, MAI, TELEPHONE FROM FOURNISSEUR;

#consulter les factures clients

SELECT CLIENT.NOM, FACTURE. ADRESSE, FACTURE.DATELIVRAISONFACTURE, FACTURE.DATEFACTURE, FACTURE.LIVRAISONEFFECTUEE, FACTURE.PRIXFACTURE
FROM FACTURE
INNER JOIN CLIENT
ON CLIENT.ID = FACTURE.ID_CLIENT
ORDER BY FACTURE.DATEFACTURE DESC;

#consulter les commandes

SELECT FOURNISSEUR.NOM, COMMANDE.DATELIVRAISONCOMMANDE, COMMANDE.DATECOMMANDE, COMMANDE.PRIXCOMMANDE, COMMANDE.LIVRAISONCOMMANDEEFFECTUEE
FROM FOURNISSEUR
INNER JOIN COMMANDE
ON COMMANDE.ID_FOURNISSEUR = FOURNISSEUR.ID
ORDER BY COMMANDE.DATECOMMANDE DESC;

#consulter les clients

SELECT NOM, PRENOM, TELEPHONE
FROM CLIENT;

#consulter les produits

SELECT EMPLACEMENT_STOCK.ALLEE, EMPLACEMENT_STOCK.PLACE, EMPLACEMENT_STOCK.ETAGE, PRODUIT.NOM, PRODUIT.POIDS, PRODUIT.PRIXVENTE
FROM PRODUIT
INNER JOINT EMPLACEMENT_STOCK
ON PRODUIT.ID_EMPLACEMENT = EMPLACEMENT_STOCK.ID;